name: Cypress-Test-Report

# Only trigger when the build workflow succeeded
on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types:
      - completed

jobs:
  cypress-test:
    runs-on: windows-latest # Use a Windows runner
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install Cypress and verify
        run: |
          npm ci
          npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome
        continue-on-error: false
